<!DOCTYPE html>

<html lang="en">
	<head>
		<title>IS218 Programming Challenge 2</title>
		
		<link rel='stylesheet' type='text/css' href='./public/styles/main.css' />
		<script type='text/javascript' src='./public/js/main.js'></script>
		
		<link rel='stylesheet' type='text/css' href='./public/styles/twitter.css' />
	</head>
	
	<body>
		
		<div id='div-twitter-toolbar'>
			
			<form id='form-tweet' class='align-vertical' method='post' action='/'>
				<label id='label-tweet' for='textarea-status'>Message:</label>
				<textarea id='textarea-status' name='status' maxlength='130'></textarea>
				<button type='submit' name='ac' value='tweet' >Tweet</button>
			</form>
			
			<ul id='ul-options'>
				<li><a href='./?ac=profile'>View Profile</a></li>
				<li><a href='./?ac=tweets'>View My Tweets</a></li>
				<li><a href='./?ac=timeline'>View Timeline</a></li>
				<li><a href='./?ac=followers'>View Followers</a></li>
				
			</ul>
		</div>
		<div id='div-content'>
			
			<?php echo($html); ?>
			
		</div>
		
		
	</body>
</html>
