<!DOCTYPE html>

<html lang="en">
	<head>
		<title>IS218 Programming Challenge 2</title>
		
		<link rel='stylesheet' type='text/css' href='./public/styles/main.css' />
		<script type='text/javascript' src='./public/js/main.js'></script>
		
		<link rel='stylesheet' type='text/css' href='./public/styles/twitter.css' />
	</head>
	
	<body>
		<div id='div-main-menu'>
			
			<ul id='ul-main-menu'>
				<li><a href='./?page=index'>School Info</a></li>
				<li><a href='./?page=twitter'>Twitter API</a></li>
			</ul>
			<div class='div-clear-both'></div>
		</div>
		
		<?php echo($html); ?>
			
	</body>
</html>
